### PR TITLE
Announcements

### PR DESCRIPTION
**Pull request by nolanw**
- [x] Scrape announcements from top of thread lists.
- [x] Scrape announcement details.
- [x] Save announcements to data store.
- [x] Show announcements in forum list in a dedicated "Announcements" section.
- [ ] Show announcement detail when tapping on announcement.
    - [x] Load plain HTML in just to see if anything's working.
    - [x] Make mustache template
    - [x] Port relevant JavaScript over from current posts view (without dependencies).
    - [ ] Test all that ported JavaScript (make some fake announcement contents as needed).
    - [x] Extract non-announcement-specific bits from `AnnouncementViewController.swift` into separate file(s).
- [x] Track whether announcement has been read (as best we can, no real identifiers for announcements).
- [x] Badge Forums tab item with unread announcement count. (Observe data store to determine count.)
- [x] Indicate which announcements are unread in Forums list.
- [x] Periodically check for new announcements. (Any thread list will have them, so pick one to load if we haven't loaded a thread list in a day.)

### CODE REVIEW

**Comment by nolanw** [comment]
@realModusOperandi ok to pass on review if you haven't got the time. I figure more code review is better than the 0 we usually do ;) but it's a volunteer project so no worries either way.

**Comment by realModusOperandi** [comment]
Oh hey, just got back from vacation and saw this. I can still take a look if you'd like, probably tomorrow, but if you want to go ahead and merge to get a beta out that's fine. I'm interested to see how this works so I'll probably look over these changes even if you don't wait for my review.

**Comment by nolanw** [comment]
I'm in no rush. Whenever you get around to it works for me. I'm sure the day I put a beta build together will be the first day in months that there are no announcements to read ;)

**Comment by realModusOperandi** [comment]
Very interesting read, but I'm by far not enough of an expert to critique. I am but a humble Java runtime developer, so this looks impressive to me.

**Comment by nolanw** [comment]
You're selling yourself short. Heck, you could probably just add a comment that said "why?" every 15 lines and we'd manage to improve something somehow :) also I'm just happy to have someone else be vaguely aware that there's some new/modified code somewhere. Thanks for taking a look.

**Pull request merged**
