### PR TITLE
Stop autoplaying imgur gifs

### PR DESCRIPTION
**Pull request by diabolik900**
Imgur saves a separate keyframe jpg for uploaded gifs, so show that
instead on load, and swap in the gif on tap.

This could use more eyes on it to make sure it works everywhere and to decide if it's enough of an improved experience.

### CODE REVIEW

**Comment by shaver** [comment]
I haven't read the diff yet, but wanted to say that this is a brilliant approach. It never even occurred to me.

**Comment by diabolik900** [comment]
Thanks. It wasn't actually my original intention when I started working on it, but as I was playing around with using their mp4 version, I noticed they have the jpgs to use for poster images. This way gets around the issues people brought up in the thread about background audio.

**Comment by nolanw** [comment]
@diabolik900 awesome!! I squashed the two commits into one and fixed some global JS var leakage. I also noticed that sometimes the tap event's `target` was the `img` element for some reason?

**Comment by diabolik900** [comment]
And you lost my third commit from like a half hour ago :argh:

I'll re-push it in a few.

**Comment by nolanw** [comment]
Oh, I'm sorry! Didn't see it at all.

Don't see it in this PR either. Weird.

Anyway yeah, push it on up to master anytime.

**Comment by diabolik900** [comment]
Pushed to master. Sorry about the messy commits. I no git too good.

**Comment by nolanw** [comment]
No worries. Any review of the commit history would show that my standards are at best highly variable.

**Pull request closed without merging**
