### PR TITLE
[WIP] Alternate app icons

### PR DESCRIPTION
**Pull request by nolanw**
Implements #656.

- [x] Pull existing app icon out of asset catalog.
- [x] Add one alternate app icon.
- [x] Add some UI in Settings tab to pick alternate app icon.
- [x] Add [remaining alternate app icons](https://drive.google.com/drive/folders/0B_J1KGlvSez7WUJNLWU3cVBYQm8?usp=sharing).
- [x] Fix issue shown in https://www.youtube.com/watch?v=zT5JhbmXqwU (after changing app icon with "Hide Sidebar in Landscape" enabled, the sidebar goes away (on iPad) or the whole interface disappears (on iPhone)).
- [x] Test phone and pad, with and without "Hide Sidebar in Landscape", in all orientations, to make sure everything still works. (Fix for above issue may have caused a regression.)

Example code to swap between bars and v:

```swift
if #available(iOS 10.3, *), UIApplication.shared.supportsAlternateIcons {
    let newIconName = UIApplication.shared.alternateIconName == nil ? "v" : nil
    UIApplication.shared.setAlternateIconName(newIconName) { error in
        if let error = error {
            Log.w("failed to change app icon: \(error)")
        }
    }
}
```

### CODE REVIEW

**Comment by realModusOperandi** [comment]
Yo that last commit doesn't really do much but I wanted to get something in there so everyone could see the direction I was thinking. Thoughts?

screen shot 2017-09-23 at 2 54 00 pm

**Comment by nolanw** [comment]
Stuck a milestone on here just to keep track of it, but I don't mean to apply any pressure! No rush, we'll ship it when it's ready.

**Comment by nolanw** [comment]
Also re: thoughts: looks like a good start!

**Comment by realModusOperandi** [comment]
Hey @nolanw any idea what could cause changing the icon to push an inescapable grey view on the root view stack?

https://www.youtube.com/watch?v=zT5JhbmXqwU

**Comment by realModusOperandi** [comment]
Hmm, problem seems to be related to "hide sidebar in landscape" being on. So something is trying to hide the sidebar, even when it's in portrait and the uh, sidebar, is the only bar.

**Comment by nolanw** [comment]
Ahaha that is wonderful. Off the top of my head, not sure what's going on there. I can take a look though.

**Comment by realModusOperandi** [comment]
It's almost like the system launching that modal dialog to indicate the icon change causes "focus" to be lost in a way we don't expect. I wonder if there's something we can do in the completion handler to keep focus where it should be...

**Comment by nolanw** [comment]
Could be some unfortunate logic in a viewWillAppear override or something. I'm poking around now.

**Comment by nolanw** [comment]
Wait so does 02736ea fix this issue? Or something unrelated?

**Comment by realModusOperandi** [comment]
Unrelated. I thought it fixed the issue because I had gone from testing on device (where hide sidebar in landscape was on) to testing in iPhone X simulator (where that setting was off.)

**Comment by nolanw** [comment]
If I set the UISplitViewController's `preferredDisplayMode` to `.automatic` then the problem goes away.

I also noticed that none of the UISplitViewControllerDelegate methods get called when the issue occurs. Whatever we're doing wrong doesn't seem to be in the delegate methods.

Also it seems like we never show the sidebar in landscape on phones where we should be? I wonder if our split view dickery has finally caught up to us. I made #660 to deal with that. In the meantime we can figure out a temporary workaround (that'll probably break "hide sidebar in landscape", which is ok because it's already broken) and finish this PR up.

**Comment by nolanw** [comment]
Interesting. On an iPad with "Hide Sidebar in Landscape" ticked, changing the app icon will close the sidebar. But since we're on iPad you can pop it back open. I wonder if whatever logic is involved there is also happening on iPhone, except there you're screwed because there's no secondary view controller waiting underneath.

**Comment by realModusOperandi** [comment]
Thanks for the clean up, been putting that off too long.

**Comment by realModusOperandi** [comment]
Hey, I noticed you've had to pretty much rewrite everything for this. The last thing I want is to make more work for you, so I'll ask: what should I read/learn before I make any more contributions? Do you have any suggestions for things I could do to better contribute? I want to help instead of hurt!

**Comment by nolanw** [comment]
I’m sorry, that’s not the impression I want to leave. You are not hurting at all! From my end it doesn’t feel like a rewrite, I thought I was taking it from like 70% complete up to 85% complete. You’ve definitely done the legwork and I appreciate the work you’ve done (and I think it’s good work!).

I’m not really sure how to best handle coordinating development on Awful. Definitely open to ideas. I can never tell if I should just jump right in to a branch like I’ve done here, or should I leave comments and expect you to do whatever additional work? Since it's a volunteer project I feel really weird tasking people like I’m somehow in charge of them. But I don’t want barge in where I’m unwelcome and stomp all over someone else’s work (pretty sure I inadvertently ran at least one person off the project years ago by doing that and I still feel bad about it).

On this PR in particular, I felt like we both kinda owned the feature and I’m excited to add it so I figured it was ok to jump in and push it forward. The main change I made was stripping the app icon cells of any responsibility whatsoever. Every time I’ve stored state like that in a view it’s ended in tears. Better to centralize all that in the collection view's data source imo. Then I implemented the todo about hiding the app icon picker on devices that don’t support it, and I realized we could load the icon data from the info.plist so we don’t have two sources of data that can get out of sync. The only other changes I made were little nitpicky things. I’m happy to go over any of the changes if it'll help.

This is a lot of words and I don’t know if they’re helpful. tl;dr you are not at all making more work for me, I appreciate the work you’re doing, and I'd love for you to keep contributing just as you are!

**Comment by realModusOperandi** [comment]
Ah, oops, I think I came across as more serious than I intended! Thanks for the response though. I really don't want to curb your enthusiasm and I'm totally okay with you moving on this if you have time! I've been off on other things this weekend.

I guess what came through was a bit of frustration at my own lack of experience. Apple development is entirely a weekend-warrior type thing for me, whereas from your posting I get the sense you have a lot more experience. So things like your example, where you know certain decisions can cause issues in the long run, are just invisible to me. I'm lucky just to get the damn thing to show up! Which is why I was concerned I was making things worse overall.

So anyways, feel free to let me know if you see me doing something that could have unintended consequences. But don't let that stop you from going in and making progress. That way I know I'm not just causing others to have to go in and resolve my messes. :)

**Comment by nolanw** [comment]
Sounds good to me! And definitely don’t hold back out of some worry about making things worse. :justpost: etc.

**Comment by nolanw** [comment]
Changed my mind on the split view weirdness after changing the icon on a phone: I think we gotta fix that before this PR is done.

**Pull request merged**
