### PR TITLE
Add Peek and Pop function to thread lists

### PR DESCRIPTION
**Pull request by drasticactions**
This PR should give you a (very much hacked together!) 3D Touch peek and pop function for threads. So you can 3D touch a thread in the thread list or bookmarks to get a peek at the thread, then hold down to pop the thread open.

I'm not that familiar with Swift, nor with how the codebase is laid out. So I hope I did it right.

Peek Thread

### CODE REVIEW

**Comment by nolanw** [comment]
Cool!

I'm concerned about requesting the next unread post for a preview, as it ends up losing the user's place in the thread. We should probably request the posts without affecting "next unread" status, which will need a small change in the AsfulForumsClient API (I think to use the `noseen` GET parameter).

**Comment by drasticactions** [comment]
I agree, but I don't know if that's so important. 

If you peek and see the preview, and you want to view the rest of the posts, you just hold down and pop the view open. It still keeps your place, because it's just using the currently instantiated view controller and loaded posts. If you decide "nah, I don't want to read more" and you let up, and it will lose your current place in the thread, but you didn't want to read whatever posts were loaded anyway.

You could also work around that by adding an option to the peek menu to have something like "keep current place" or something like that.

I'm cool with whatever though. If it's something I can change I'll be happy to do so. So long as it does not involve Objective-C, because you got me making Swift code and that's more than enough.

**Comment by shaver** [comment]
On Sun, Sep 27, 2015 at 12:14 PM, Tim Miller <notifications@github.com>
wrote:

> If you peek and see the preview, and you want to view the rest of the
> posts, you just hold down and pop the view open. It still keeps your place,
> because it's just using the currently instantiated view controller and
> loaded posts. If you decide "nah, I don't want to read more" and you let
> up, and it will lose your current place in the thread, but you didn't want
> to read whatever posts were loaded anyway.
>
>
I think that's not quite right. I might peek and see that the post is
longer than I can read right then, for example. In general, peeking
shouldn't affect state IMO.

**Comment by drasticactions** [comment]
So I updated AwfulForumsClient to use the 'noseen' parameter, and updated the PostPageViewController.loadPage function to use said parameter. This should fix it so that if you peek at the thread it won't count those posts as read.

However, if do pop the thread open, unless you refresh the thread while you're there, it still won't count those posts. We could fire a command after the thread has been popped to say that the last post in the thread is last read, or something along those lines, but I'm not sure if that would go in the UIViewControllerPreviewingDelegate controller or not. 

But in any case, it should at least basically work ;)

**Pull request closed without merging**
